### ISSUE TITLE
dependentAssembly and assemblyIdentity not updated

### ISSUE THREAD

**Issue by cuperman007** [deadlydog/Set-ProjectFilesClickOnceVersion#4]
Hi @deadlydog 

I've followed your blog post to create a new CI/CD pipeline for a simple dummy WPF application. I have the build working (with an updated version number) and this is deploying back a shared drive on my laptop (via DevOps deployment groups). 

In the published folder I can see a versioned folder sitting in `Applications Files`, for example;
`Publish\Application Files\DeploymentTesting.WpfApp_1_0_0_13`

I can install the application from `Publish\setup.exe` and it is working correctly. 

When I commit an update I can see both CI and CD pipes get completed and a new version of the application is been deployed to my local publish folder, for example;
`Publish\Application Files\DeploymentTesting.WpfApp_1_0_0_14`. 

When I restart the installed application the check is running and then the old version (1.0.0.13) is starting. 

Inside the `Publish\DeploymentTesting.WpfApp.application` file the `dependentAssembly` and `assemblyIdentity` nodes are still referencing the original versioned folder:
`
    <dependency>  
        <dependentAssembly dependencyType="install" codebase="Application Files\DeploymentTesting.WpfApp_1_0_0_13\DeploymentTesting.WpfApp.exe.manifest" size="8852">  
            <assemblyIdentity name="DeploymentTesting.WpfApp.exe" version="1.0.0.13" publicKeyToken="d5e816d8c223a95a" language="neutral" processorArchitecture="msil" type="win32" />  
`

My understanding it that this should be updated and created automatically via the build step with `/target:Publish`. 

I'd really appreciate your thoughts on this. Do you have any ideas where I might have gone wrong?

Thanks,
Mark

**Comment by cuperman007** [comment]
I carried on fiddling and found another important setting. In the Release **Copy files** task there is an advanced option to **Overwrite** files. Check this option, and we are good. Make sure the **Clean Target Folder** option is not set as this will kill any older versions and prevent rollback.

No further changes needed. 

Thanks very much for your well written article 👍 

Best regards
Mark

**Comment by deadlydog** [comment]
Glad to hear you got it figured out 👍
